### ISSUE TITLE
[BUG] <Fatigue data uploading>

### ISSUE THREAD

**Issue by vsdharun** [EPFL-ENAC/CCFatiguePlatform#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/EPFL-ENAC/CCFatiguePlatform/assets/81630367/5acee4cd-62a1-4146-9cf1-0022f8eee0be)
 Although I have the mandatory columns in my files, there are errors.

![image](https://github.com/EPFL-ENAC/CCFatiguePlatform/assets/81630367/624cfa68-52eb-4b54-a75a-34d2bf477d7a)
It seems the columns were dropped. Thatswhy, I am getting the error.

I have attached the zip file data. could you let me know, what is wrong here?
[TST_Srinivasan_2022-04_FA.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/15286899/TST_Srinivasan_2022-04_FA.zip)

### Expected Behavior

I expect no error while uploading this zip file in CC Fatigue platform.

### Environment

```Markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
Hello @vsdharun I've fixed your dataset. You had two problems.

1) the xls file (metadata) was not correct (the first column was missing)
2) the 20th csv file had bad column names
3) all the csv file had a '#' instead of a number: I replaced the # by 1
[TST_Srinivasan_2022-04_FA.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/15291316/TST_Srinivasan_2022-04_FA.zip)

Here is the file btw, I'll handle the upload, no need to create a new Issue, I'll send you an email, when it's up and running

**Comment by vsdharun** [comment]
@guilbep Thanks and looking forward to see this data in the platform :)

**Comment by guilbep** [comment]
@vsdharun Hello!  It's all good! https://ccfatigue.epfl.ch/fatigue_database/tests_selection?exp=8

Have fun
